---
- name: Add beats key
  apt_key: id=D88E42B4 keyserver=pgp.mit.edu state=present

- name: Add beats repo
  apt_repository: repo='deb {{ beats_repository_url }} stable main' state=present

- name: Install topbeat
  apt: pkg={{ topbeat_package }} state=present update_cache=yes
