---
- name: Download topbeat 1.0.0
  get_url:
    url: "https://download.elastic.co/beats/topbeat/topbeat_1.0.0_amd64.deb"
    dest: "/tmp"

- name: Install topbeat 1.0.0
  apt:
    deb: "/tmp/topbeat_1.0.0_amd64.deb"
