---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install httplib2
  pip:
    name: httplib2

#- name: Check existence of topbeat index template
#  uri:
#    url: "{{ topbeat_elasticsearch_url }}/_template/topbeat"
#    method: HEAD
#    status_code:
#      - 200
#      - 404
#  register: topbeat_index_template_check
#  when: topbeat_output_elasticsearch == true
#
#- name: Read default templates config
#  shell: cat /etc/topbeat/topbeat.template.json
#  register: contents
#
#- name: Create elasticsearch index template for topbeat
#  uri:
#    url: "{{ topbeat_elasticsearch_url }}/_template/topbeat"
#    method: PUT
#    body: "{{ contents|to_json }}"
#    status_code: 200
#  when: topbeat_output_elasticsearch == true and topbeat_index_template_check.status == 404
#  notify:
#    - restart topbeat

- name: Enable topbeat at boot
  service:
    name: topbeat
    enabled: yes
  notify:
    - restart topbeat

- name: Configure topbeat
  template:
    src: "topbeat.yml.j2"
    dest: "/etc/topbeat/topbeat.yml"
  notify: restart topbeat


